services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--log-level=info"
      - "--set=decision_logs.console=true"
      - "/policies"
    volumes:
      - ./policies:/policies
