package uk.gov.justice.laa.portal.landingpage.entity;

public enum EventType {
    CREATE_USER,
    UPDATE_USER,
    REASSIGN_USER_FIRM,
    USER_DELETE_EXECUTED,
    USER_DELETE_ATTEMPT,
    SWITCH_FIRM,
    UPDATE_LAA_APP_METADATA,
    DELETE_LAA_APP_ROLE,
    SYNCHRONISE_LAA_APPS,
    CREATE_LAA_APP_ROLE,
    BULK_DISABLE_FIRM_USERS,
    REACTIVATE_REQ_DELEGATE_ENABLE_USER_SUBMIT,
    REACTIVATE_REQ_DELEGATE_ENABLE_USER_APPROVED,
    REACTIVATE_REQ_DELEGATE_ENABLE_USER_REJECTED,
    REACTIVATE_REQ_DELEGATE_ENABLE_USER_UPDATED,
}
