secret:
  enabled: true

  rules:
    - id: CUSTOM_API_KEY
      pattern: (?i)api[_-]?key\s*[:=]\s*[\'"]?[a-z0-9]{32,}[\'"]?
      keywords:
        - password
        - passwd
        - pwd
        - secret
        - key
        - token
        - auth
        - credential
        - access
        - login
        - signin
        - api_key
        - api-key

      severity: HIGH
      description: Custom API Key format

  # Optional: Exclude specific paths
  # ignoreFiles:
  #   - path: tests/
