apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${NAMESPACE}-service-monitor
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: laa-landing-page
  namespaceSelector:
    matchNames:
      - ${NAMESPACE}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s