apiVersion: batch/v1
kind: Job
metadata:
  name: zap-scan
  namespace: ${NAMESPACE}
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: zap
          image: ghcr.io/zaproxy/zaproxy:stable
          volumeMounts:
            - name: zap-wrk
              mountPath: /zap/wrk
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
          command:
            - /bin/sh
            - -c
            - zap-baseline.py -t http://laa-landing-page.${NAMESPACE}.svc.cluster.local -I -w report.md && echo "===== BEGIN ZAP REPORT.MD =====" && cat /zap/wrk/report.md && echo "===== END ZAP REPORT.MD ====="
      volumes:
        - name: zap-wrk
          emptyDir: {}
      restartPolicy: Never
