name: Ash OpenGrep & Checkov Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ash-opengrep-and-checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: OpenGrep Scan
        continue-on-error: true
        uses: semgrep/semgrep-action@v1
        with:
          config: p/default

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true
          soft_fail: true