name: Ash Grype Scan & Syft SBOM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build . --file Dockerfile-WorkFlow --tag laa-landing-page:latest --progress=plain --no-cache
      
      - name: Grype Scan
        uses: anchore/scan-action@v7
        with:
          image: football-data-xg:latest
          fail-build: false
          output-format: json
          output-file: grype-report.json
      
      - name: Generate Syft SBOM
        uses: anchore/sbom-action@v0
        with:
          image: football-data-xg:latest
          format: spdx-json
          output-file: syft-sbom.spdx.json
      
      - name: Upload Grype Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grype-scan-report
          path: grype-report.json
      
      - name: Upload Syft SBOM
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: syft-sbom
          path: syft-sbom.spdx.json