name: 'Jira Ticket Check'

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check for Jira Ticket in PR Title'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # 8.0
        with:
          script: |
            const title = context.payload.pull_request.title;
            // Matches "stb-123", "STB-123", "Feature/STB-999", etc.
            const regex = /STB-\d+/i; 
            
            if (!regex.test(title)) {
              core.setFailed('Please add a Jira ticket ID to the PR title (e.g., STB-123).');
            }