name: 'Jira Ticket Check'

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check for Jira Ticket in PR Title'
        uses: deepakputhraya/action-pr-title@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          regex: '([A-Z]+-[0-9]+)'
          allowed_prefixes: 'STB'
          prefix_case_sensitive: false
          verbal_description: 'Please add a Jira ticket ID to the PR title (e.g., STB-123).'