name: Linter Check

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

permissions:
  contents: read

jobs:
  lint:
    name: Run Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest checkStyleIntegrationTest checkstylePlaywrightTest
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: checkstyle-report
          path: target/checkstyle/*
          retention-days: 15
