name: Linter Check

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  lint:
    name: Run Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest checkStyleIntegrationTest checkstylePlaywrightTest
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: checkstyle-report
          path: target/checkstyle/*
          retention-days: 15
