name: TruffleHog secret scan

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  push:
  schedule:
    - cron: "53 0 * * *" # run once a day at 00:53 UTC

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
    - name: TruffleHog scan
      uses: trufflesecurity/trufflehog@27b0417c16317ca9a472a9a8092acce143b49c55 # 3.95.9
      with:
        version: 3.95.4@sha256:2df7b5f8ec308946dff88927d4a2c3426ebc4efed15fed9c63294e13f3ccbb29
        extra_args: --results=verified
