name: Tests

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant Execute Permission for Gradle
        run: chmod +x gradlew

      - name: Run Coverage
        run: |
          ./gradlew test
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@50d3aff4548aa991e6753342d9ba291084e63848 # v1.7.2
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/**/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 85
          min-coverage-changed-files: 85
          title: Code Coverage
          update-comment: true

      - name: Fail PR if overall coverage is less than 85%
        if: ${{ steps.jacoco.outputs.coverage-overall < 85 }}
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            core.setFailed('Overall unit test coverage is less than 85%!')    

      - name: Run IntegrationTest
        run: |
          ./gradlew integrationTest

      - name: Run PlaywrightTest
        id: playwright
        continue-on-error: true
        run: |
          APP_PLAYWRIGHT_HEADLESS=true ./gradlew playwrightTest

      - name: Upload Playwright failure artifacts
        if: steps.playwright.outcome == 'failure'
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: playwright-failures
          path: |
            screenshots/**
            build/playwright-report.html

      - name: Fail job if Playwright tests failed
        if: steps.playwright.outcome == 'failure'
        run: exit 1
