name: Trivy Vulnerability Scan
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - closed

jobs:
  install_trivy:
    runs-on: ubuntu-latest
    env:
      MY_GITHUB_ACTOR: ${{ secrets.MY_GITHUB_ACTOR }}
      MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
      # || true allows it to pass if vulns are found
      - name: Build Docker image for Trivy to check Docker images for vulnerabilities
        run: docker build . --file Dockerfile-WorkFlow --tag laa-landing-page:latest --progress=plain --no-cache

      - name: Container Image
        run: trivy image --severity CRITICAL --format table --no-progress --output trivy-image.txt laa-landing-page:latest  || true
      
      - name: List all file paths inside Docker container
        run: |
          docker run --rm laa-landing-page:latest find / -type f 2>/dev/null

      - name: Secrets
        run: trivy fs --security-checks secret --format table --no-progress --output trivy-secrets.txt . || true

      - name: IaC
        run: trivy config --severity CRITICAL --format table --output trivy-iac.txt . || true

      - name: Dependencies
        run: trivy fs --severity CRITICAL --security-checks vuln --format table --output trivy-deps.txt . || true

      - name: Dockerfile
        run: trivy dockerfile --format table --exit-code 1 Dockerfile-WorkFlow > trivy-dockerfile.txt || true

      - name: Display all Trivy scan results
        run: |
          echo "===== Container Image Scan ====="
          cat trivy-image.txt || echo "No image scan results."

          echo ""
          echo "===== Secrets Scan ====="
          cat trivy-secrets.txt || echo "No secrets scan results."

          echo ""
          echo "===== IaC Scan ====="
          cat trivy-iac.txt || echo "No IaC scan results."

          echo ""
          echo "===== Dependency Scan ====="
          cat trivy-deps.txt || echo "No dependency scan results."

          echo ""
          echo "===== Dockerfile Scan ====="
          cat trivy-dockerfile.txt || echo "No Dockerfile scan results."