name: ZAP DAST Scan

on:
  push:
    branches:
      - main
      - zap-dast-test
  workflow_dispatch:

jobs:
  zap_scan:
    name: Run ZAP DAST Scan Against Live App
    runs-on: ubuntu-latest

    steps:
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://laa-landing-page-dev.apps.live.cloud-platform.service.justice.gov.uk/'
          cmd_options: '-a -j'
          fail_action: false
        env:
          NUMBER: ${{ github.event.issue.number }}
          URL: ${{ github.event.issue.issue_url }}

      - name: Slack notification
        uses: slackapi/slack-github-action@v1.23.0
        with:
            channel-id: 'laa-zap-scan-notifications'
            slack-message: "A new issue number: ${{ NUMBER }} and url: ${{ URL }} has been created"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_html.html
            report_json.json
