name: ZAP DAST Weeky Full Scan

on:
  schedule:
    - cron: '0 8 * * SUN'

jobs:
  zap_scan:
    name: Run Full ZAP DAST Scan Against Live App
    runs-on: ubuntu-latest

    steps:
      - name: Run ZAP Weekly Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://laa-landing-page-dev.apps.live.cloud-platform.service.justice.gov.uk/'
          cmd_options: '-a -j -m 120'
          fail_action: false

      - name: Upload Weekly Scan ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: weekly-zap-report
          path: |
            report_html.html
            report_json.json
